title: arbatov.me
timezone: UTC
collections:
  links:
    title: Links
    output: false
  posts:
    title: Posts
    output: false
  uploads:
    title: Uploads
    output: true
email: vlad@arbatov.me
description: Artificial Intelligence expert. Founder â€” arb.digital.
baseurl: null
url: 'https://arbatov.me'
twitter_username: vladzima
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
